version: '3.8'

services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    volumes:
      - ./gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - OPENVPN_USER=${VPN_USER}
      - OPENVPN_PASSWORD=${VPN_PASS}
      - TZ=${TZ}
      - SERVER_COUNTRIES=Netherlands
    ports:
      - "8080:8080"
      - 6881:6881      # QB
      - 6881:6881/udp  # QB
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./downloads:/downloads
    restart: unless-stopped

  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: bridge
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM}
    ports:
      - "32400:32400"
    volumes:
      - ./plex/movies:/plex/movies
      - ./plex/series:/plex/series
    restart: unless-stopped
